### ISSUE TITLE
Peer-review

### ISSUE THREAD

**Issue by Runqing2022** [COMPUTE-Jupyter-course/project-for-compute-jupyter-2022-jstrobaek#1]
## Documentation
- [x] title and abstract of the project (max 300 words)
- [x] includes instructions on how to run the notebook
- [x] #2
        - after installing the environment.yml file, the environment name is **xl_viz**. It would be helpful if it could be mentioned somewhere.
- [x] includes a brief explanation of the reason each package/library was used
- [x] #8
       - there's only text, but I assume it's enough since it looks like there's no need to add more explanation.
- [x] #3
      - there's always an error in cell 22, 'list index out of range'
      - for cell 24 shows 'No such file or directory:', probably my problem

## Input/Output:
- [x] uses pandas to read large data sets or numpy to load data from text files
- [x] uses pandas to save to disk the processed or generated data

## Scientific computing/data processing:
- [x] performs numerical operations (numpy, scipy, pandas) or manipulates, groups, and aggregates a data set (pandas)

## Data visualization:
- [x] #4
- [x] produces publication-ready quality figures (see here for an editorial guide on Graphical Excellence):
- [x] #5
      - **not sure**
- [x] the axes are labeled
- [x] the font sizes are sufficiently large
- [x] #6
      - **not sure**

## Version control, sharing, and archiving:
- [x] #7

**Comment by jstrobaek** [comment]
All issues dealt with: closing issue and thereby handing in the finalized version.

**Comment by jstrobaek** [comment]
All issues dealt with: closing this issue and thereby handing in the finalized version.
